-- ============================================================
--  MIS FINANZAS — Esquema de base de datos (Oracle)
--  Generado automáticamente con tools/export_schema.sh
--  NO editar a mano — volver a correr el script tras cada cambio
-- ============================================================

-- ── TABLAS ──────────────────────────────────────────────────

-- USUARIOS
CREATE TABLE "MISGASTOS"."USUARIOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(200) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PASSWORD_HASH" VARCHAR2(256) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"ONBOARDING_COMPLETADO" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "CHK_USUARIO_ACTIVO" CHECK (ACTIVO IN (0,1)) ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("EMAIL")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

-- CATEGORIAS
CREATE TABLE "MISGASTOS"."CATEGORIAS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USUARIO_ID" NUMBER NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"EMOJI" VARCHAR2(40 CHAR) COLLATE "USING_NLS_COMP", 
	"COLOR" VARCHAR2(7) COLLATE "USING_NLS_COMP" DEFAULT '#888780', 
	"ES_SISTEMA" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "CHK_CAT_SISTEMA" CHECK (ES_SISTEMA IN (0,1)) ENABLE, 
	 CONSTRAINT "CHK_CAT_ACTIVO" CHECK (ACTIVO IN (0,1)) ENABLE, 
	 CONSTRAINT "CHK_CAT_COLOR" CHECK (REGEXP_LIKE(COLOR, '^#[0-9A-Fa-f]{6}$')) ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

-- CUENTAS
CREATE TABLE "MISGASTOS"."CUENTAS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USUARIO_ID" NUMBER NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"BANCO" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"TIPO_PAGO" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"MONEDA" VARCHAR2(10) COLLATE "USING_NLS_COMP" DEFAULT 'MXN' NOT NULL ENABLE, 
	"COLOR" VARCHAR2(7) COLLATE "USING_NLS_COMP" DEFAULT '#888780', 
	"ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"OPERA_GASTOS" NUMBER(1,0) DEFAULT 1, 
	"CATEGORIA_LIQ" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "CHK_CUENTA_ACTIVO" CHECK (ACTIVO IN (0,1)) ENABLE, 
	 CONSTRAINT "CHK_CUENTA_COLOR" CHECK (REGEXP_LIKE(COLOR, '^#[0-9A-Fa-f]{6}$')) ENABLE, 
	 CONSTRAINT "CHK_CUENTA_TIPO" CHECK (TIPO_PAGO IN (
        'Efectivo','Tarjeta débito','Tarjeta crédito',
        'Transferencia','CoDi','Casa de bolsa',
        'Crypto','Ahorro','Plan de pensión','Otros'
    )) ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

-- DESTINATARIOS
CREATE TABLE "MISGASTOS"."DESTINATARIOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USUARIO_ID" NUMBER NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"EMOJI" VARCHAR2(40 CHAR) COLLATE "USING_NLS_COMP", 
	"COLOR" VARCHAR2(7) COLLATE "USING_NLS_COMP" DEFAULT '#888780', 
	"ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "CHK_DEST_ACTIVO" CHECK (ACTIVO IN (0,1)) ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

-- ESTADOS_TARJETA
CREATE TABLE "MISGASTOS"."ESTADOS_TARJETA" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USUARIO_ID" NUMBER NOT NULL ENABLE, 
	"TARJETA_ID" NUMBER NOT NULL ENABLE, 
	"ANIO" NUMBER(4,0) NOT NULL ENABLE, 
	"MES" NUMBER(2,0) NOT NULL ENABLE, 
	"FECHA_CORTE" DATE, 
	"FECHA_LIMITE" DATE, 
	"ADEUDO_ANTERIOR" NUMBER(18,2) DEFAULT 0, 
	"CARGOS_REGULARES" NUMBER(18,2) DEFAULT 0, 
	"CARGOS_MESES" NUMBER(18,2) DEFAULT 0, 
	"INTERESES" NUMBER(18,2) DEFAULT 0, 
	"COMISIONES" NUMBER(18,2) DEFAULT 0, 
	"IVA" NUMBER(18,2) DEFAULT 0, 
	"PAGO_MINIMO" NUMBER(18,2) DEFAULT 0, 
	"PAGO_PNGI" NUMBER(18,2) DEFAULT 0, 
	"PAGO_REAL" NUMBER(18,2), 
	"TASA" NUMBER(6,2), 
	"SALDO_REGULAR" NUMBER(18,2) DEFAULT 0, 
	"SALDO_MESES" NUMBER(18,2) DEFAULT 0, 
	"DEUDOR_TOTAL" NUMBER(18,2) DEFAULT 0, 
	"NOTAS" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UK_ESTADO_TARJETA" UNIQUE ("TARJETA_ID", "ANIO", "MES")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

-- FUENTES_INGRESO
CREATE TABLE "MISGASTOS"."FUENTES_INGRESO" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USUARIO_ID" NUMBER NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"TIPO" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"FRECUENCIA" VARCHAR2(20) COLLATE "USING_NLS_COMP" DEFAULT 'Variable' NOT NULL ENABLE, 
	"MONEDA" VARCHAR2(10) COLLATE "USING_NLS_COMP" DEFAULT 'MXN' NOT NULL ENABLE, 
	"COLOR" VARCHAR2(7) COLLATE "USING_NLS_COMP" DEFAULT '#1D9E75', 
	"ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "CHK_FUENTE_TIPO" CHECK (TIPO IN (
        'Salario','Renta','Inversión','Préstamo','Otro'
    )) ENABLE, 
	 CONSTRAINT "CHK_FUENTE_FREQ" CHECK (FRECUENCIA IN (
        'Mensual','Quincenal','Semanal','Variable','Único'
    )) ENABLE, 
	 CONSTRAINT "CHK_FUENTE_ACTIVO" CHECK (ACTIVO IN (0,1)) ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

-- PRESTATARIOS
CREATE TABLE "MISGASTOS"."PRESTATARIOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USUARIO_ID" NUMBER NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(150) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CAPITAL_ORIGINAL" NUMBER(18,2) DEFAULT 0 NOT NULL ENABLE, 
	"CAPITAL_RECUPERADO" NUMBER(18,2) DEFAULT 0 NOT NULL ENABLE, 
	"TASA_INTERES" NUMBER(6,2) DEFAULT 0, 
	"FECHA_PRESTAMO" DATE, 
	"FECHA_VENCIMIENTO" DATE, 
	"ESTATUS" VARCHAR2(20) COLLATE "USING_NLS_COMP" DEFAULT 'Activo' NOT NULL ENABLE, 
	"NOTAS" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"PAGOS_POR_ANIO" NUMBER DEFAULT 12 NOT NULL ENABLE, 
	"NUMERO_PAGOS" NUMBER, 
	 CONSTRAINT "CHK_PREST_ESTATUS" CHECK (ESTATUS IN ('Activo','Liquidado','Vencido','Incobrable')) ENABLE, 
	 CONSTRAINT "CHK_PREST_CAPITAL" CHECK (CAPITAL_ORIGINAL >= 0) ENABLE, 
	 CONSTRAINT "CHK_PREST_RECUP" CHECK (CAPITAL_RECUPERADO >= 0) ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

-- SALDOS_MES
CREATE TABLE "MISGASTOS"."SALDOS_MES" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USUARIO_ID" NUMBER NOT NULL ENABLE, 
	"CUENTA_ID" NUMBER NOT NULL ENABLE, 
	"ANIO" NUMBER(4,0) NOT NULL ENABLE, 
	"MES" NUMBER(2,0) NOT NULL ENABLE, 
	"SALDO" NUMBER(18,2) DEFAULT 0, 
	"MONEDA" VARCHAR2(3) COLLATE "USING_NLS_COMP" DEFAULT 'MXN', 
	"TASA_CAMBIO" NUMBER(10,4) DEFAULT 1, 
	"SALDO_MXN" NUMBER(18,2), 
	"NOTAS" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UK_SALDOMES" UNIQUE ("USUARIO_ID", "CUENTA_ID", "ANIO", "MES")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

-- SESIONES
CREATE TABLE "MISGASTOS"."SESIONES" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USUARIO_ID" NUMBER NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(150) COLLATE "USING_NLS_COMP", 
	"NOMBRE" VARCHAR2(200) COLLATE "USING_NLS_COMP", 
	"DEVICE" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"IP" VARCHAR2(45) COLLATE "USING_NLS_COMP", 
	"LOGIN_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"LAST_SEEN_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"LOGOUT_AT" TIMESTAMP (6), 
	"ACTIVA" NUMBER(1,0) DEFAULT 1, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

-- TARJETAS_CREDITO
CREATE TABLE "MISGASTOS"."TARJETAS_CREDITO" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USUARIO_ID" NUMBER NOT NULL ENABLE, 
	"CUENTA_ID" NUMBER NOT NULL ENABLE, 
	"LIMITE_CREDITO" NUMBER(18,2) NOT NULL ENABLE, 
	"DIA_CORTE" NUMBER(2,0), 
	"DIAS_PARA_PAGO" NUMBER(2,0) DEFAULT 20, 
	"TASA_ANUAL" NUMBER(6,2), 
	"ACTIVO" NUMBER(1,0) DEFAULT 1, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UK_TARJETA_CUENTA" UNIQUE ("CUENTA_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

-- TIPOS_CAMBIO
CREATE TABLE "MISGASTOS"."TIPOS_CAMBIO" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"MONEDA_ORIGEN" VARCHAR2(10) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"MONEDA_DESTINO" VARCHAR2(10) COLLATE "USING_NLS_COMP" DEFAULT 'MXN' NOT NULL ENABLE, 
	"TASA" NUMBER(18,6) NOT NULL ENABLE, 
	"FUENTE" VARCHAR2(50) COLLATE "USING_NLS_COMP" DEFAULT 'exchangerate-api' NOT NULL ENABLE, 
	"FECHA_CONSULTA" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"FECHA_DIA" DATE GENERATED ALWAYS AS (TRUNC("FECHA_CONSULTA")) VIRTUAL , 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

-- COMPRAS_MSI
CREATE TABLE "MISGASTOS"."COMPRAS_MSI" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USUARIO_ID" NUMBER NOT NULL ENABLE, 
	"TARJETA_ID" NUMBER NOT NULL ENABLE, 
	"ADICIONAL_ID" NUMBER, 
	"DESCRIPCION" VARCHAR2(200) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"DESTINATARIO_ID" NUMBER, 
	"MONTO_TOTAL" NUMBER(18,2) NOT NULL ENABLE, 
	"NUM_MESES" NUMBER(3,0) NOT NULL ENABLE, 
	"MENSUALIDAD" NUMBER(18,2) NOT NULL ENABLE, 
	"FECHA_COMPRA" DATE, 
	"PRIMER_ANIO" NUMBER(4,0) NOT NULL ENABLE, 
	"PRIMER_MES" NUMBER(2,0) NOT NULL ENABLE, 
	"GENERA_GASTO" NUMBER(1,0) DEFAULT 1, 
	"ACTIVO" NUMBER(1,0) DEFAULT 1, 
	"NOTAS" VARCHAR2(300) COLLATE "USING_NLS_COMP", 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

-- TARJETAS_ADICIONALES
CREATE TABLE "MISGASTOS"."TARJETAS_ADICIONALES" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USUARIO_ID" NUMBER NOT NULL ENABLE, 
	"TARJETA_ID" NUMBER NOT NULL ENABLE, 
	"DESTINATARIO_ID" NUMBER NOT NULL ENABLE, 
	"TERMINACION" VARCHAR2(4) COLLATE "USING_NLS_COMP", 
	"ACTIVO" NUMBER(1,0) DEFAULT 1, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

-- GASTOS
CREATE TABLE "MISGASTOS"."GASTOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USUARIO_ID" NUMBER NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(200) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"MONTO" NUMBER(18,2) NOT NULL ENABLE, 
	"MONEDA" VARCHAR2(10) COLLATE "USING_NLS_COMP" DEFAULT 'MXN' NOT NULL ENABLE, 
	"MONTO_MXN" NUMBER(18,2), 
	"TASA_CAMBIO" NUMBER(18,6) DEFAULT 1, 
	"FECHA" DATE NOT NULL ENABLE, 
	"CATEGORIA_ID" NUMBER NOT NULL ENABLE, 
	"CUENTA_ID" NUMBER NOT NULL ENABLE, 
	"DESTINATARIO_ID" NUMBER, 
	"NOTAS" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"DEVICE" VARCHAR2(20) COLLATE "USING_NLS_COMP" DEFAULT 'web', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"ADICIONAL_ID" NUMBER, 
	 CONSTRAINT "CHK_GASTO_MONTO" CHECK (MONTO > 0) ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

-- INGRESOS
CREATE TABLE "MISGASTOS"."INGRESOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USUARIO_ID" NUMBER NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(200) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"TIPO" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"FUENTE_ID" NUMBER NOT NULL ENABLE, 
	"MONTO" NUMBER(18,2) NOT NULL ENABLE, 
	"MONEDA" VARCHAR2(10) COLLATE "USING_NLS_COMP" DEFAULT 'MXN' NOT NULL ENABLE, 
	"MONTO_MXN" NUMBER(18,2), 
	"TASA_CAMBIO" NUMBER(18,6) DEFAULT 1, 
	"FECHA" DATE NOT NULL ENABLE, 
	"CUENTA_ID" NUMBER NOT NULL ENABLE, 
	"NOTAS" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"DEVICE" VARCHAR2(20) COLLATE "USING_NLS_COMP" DEFAULT 'web', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "CHK_ING_TIPO" CHECK (TIPO IN (
        'Salario','Renta','Inversión','Préstamo','Otro'
    )) ENABLE, 
	 CONSTRAINT "CHK_ING_MONTO" CHECK (MONTO > 0) ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

-- PAGOS_PRESTAMO
CREATE TABLE "MISGASTOS"."PAGOS_PRESTAMO" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"INGRESO_ID" NUMBER NOT NULL ENABLE, 
	"PRESTATARIO_ID" NUMBER NOT NULL ENABLE, 
	"CAPITAL" NUMBER(18,2) DEFAULT 0 NOT NULL ENABLE, 
	"INTERESES" NUMBER(18,2) DEFAULT 0 NOT NULL ENABLE, 
	"FECHA" DATE NOT NULL ENABLE, 
	"NOTAS" VARCHAR2(300) COLLATE "USING_NLS_COMP", 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "CHK_PAGO_CAPITAL" CHECK (CAPITAL >= 0) ENABLE, 
	 CONSTRAINT "CHK_PAGO_INTERESES" CHECK (INTERESES >= 0) ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

-- ── LLAVES FORÁNEAS ─────────────────────────────────────────

-- FKs de CATEGORIAS
ALTER TABLE "MISGASTOS"."CATEGORIAS" ADD CONSTRAINT "FK_CAT_USUARIO" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "MISGASTOS"."USUARIOS" ("ID") ENABLE;

-- FKs de CUENTAS
ALTER TABLE "MISGASTOS"."CUENTAS" ADD CONSTRAINT "FK_CUENTA_USUARIO" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "MISGASTOS"."USUARIOS" ("ID") ENABLE;

-- FKs de DESTINATARIOS
ALTER TABLE "MISGASTOS"."DESTINATARIOS" ADD CONSTRAINT "FK_DEST_USUARIO" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "MISGASTOS"."USUARIOS" ("ID") ENABLE;

-- FKs de FUENTES_INGRESO
ALTER TABLE "MISGASTOS"."FUENTES_INGRESO" ADD CONSTRAINT "FK_FUENTE_USUARIO" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "MISGASTOS"."USUARIOS" ("ID") ENABLE;

-- FKs de PRESTATARIOS
ALTER TABLE "MISGASTOS"."PRESTATARIOS" ADD CONSTRAINT "FK_PREST_USUARIO" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "MISGASTOS"."USUARIOS" ("ID") ENABLE;

-- FKs de GASTOS
ALTER TABLE "MISGASTOS"."GASTOS" ADD CONSTRAINT "FK_GASTO_USUARIO" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "MISGASTOS"."USUARIOS" ("ID") ENABLE;
  ALTER TABLE "MISGASTOS"."GASTOS" ADD CONSTRAINT "FK_GASTO_CAT" FOREIGN KEY ("CATEGORIA_ID")
	  REFERENCES "MISGASTOS"."CATEGORIAS" ("ID") ENABLE;
  ALTER TABLE "MISGASTOS"."GASTOS" ADD CONSTRAINT "FK_GASTO_CUENTA" FOREIGN KEY ("CUENTA_ID")
	  REFERENCES "MISGASTOS"."CUENTAS" ("ID") ENABLE;
  ALTER TABLE "MISGASTOS"."GASTOS" ADD CONSTRAINT "FK_GASTO_DEST" FOREIGN KEY ("DESTINATARIO_ID")
	  REFERENCES "MISGASTOS"."DESTINATARIOS" ("ID") ENABLE;

-- FKs de INGRESOS
ALTER TABLE "MISGASTOS"."INGRESOS" ADD CONSTRAINT "FK_ING_USUARIO" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "MISGASTOS"."USUARIOS" ("ID") ENABLE;
  ALTER TABLE "MISGASTOS"."INGRESOS" ADD CONSTRAINT "FK_ING_FUENTE" FOREIGN KEY ("FUENTE_ID")
	  REFERENCES "MISGASTOS"."FUENTES_INGRESO" ("ID") ENABLE;
  ALTER TABLE "MISGASTOS"."INGRESOS" ADD CONSTRAINT "FK_ING_CUENTA" FOREIGN KEY ("CUENTA_ID")
	  REFERENCES "MISGASTOS"."CUENTAS" ("ID") ENABLE;

-- FKs de PAGOS_PRESTAMO
ALTER TABLE "MISGASTOS"."PAGOS_PRESTAMO" ADD CONSTRAINT "FK_PAGO_INGRESO" FOREIGN KEY ("INGRESO_ID")
	  REFERENCES "MISGASTOS"."INGRESOS" ("ID") ENABLE;
  ALTER TABLE "MISGASTOS"."PAGOS_PRESTAMO" ADD CONSTRAINT "FK_PAGO_PRESTATARIO" FOREIGN KEY ("PRESTATARIO_ID")
	  REFERENCES "MISGASTOS"."PRESTATARIOS" ("ID") ENABLE;

